apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backstage
  description: Backstage Project
  annotations:
    github.com/project-slug: mathieu-benoit/deploy-backstage-with-score
  links:
    - url: https://github.com/mathieu-benoit/deploy-backstage-with-score
      title: Repository
      icon: github
spec:
  owner: user:guest
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
  description: Backstage Frontend
  annotations:
    github.com/project-slug: mathieu-benoit/deploy-backstage-with-score
  tags:
    - nginx
    - javascript
    - html
    - typescript
    - css
  links:
    - url: https://github.com/mathieu-benoit/deploy-backstage-with-score
      title: Source code
      icon: github
spec:
  type: website
  lifecycle: experimental
  owner: user:guest
  system: backstage
  dependsOn:
  - 'resource:dns'
  - 'component:backend'
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns
  description: DNS
spec:
  type: dns
  owner: user:guest
  system: backstage
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend
  description: Backstage Backend
  annotations:
    github.com/project-slug: mathieu-benoit/deploy-backstage-with-score
  tags:
    - javascript
    - nodejs
  links:
    - url: https://github.com/mathieu-benoit/deploy-backstage-with-score
      title: Source code
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  system: backstage
  dependsOn:
  - 'resource:postgres'
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgres
  description: PostgreSQL
spec:
  type: database
  owner: user:guest
  system: backstage
