---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
    annotations:
        github.com/project-slug: mathieu-benoit/deploy-backstage-with-score
    description: backstage
    links:
        - icon: github
          title: Repository
          url: https://github.com/mathieu-benoit/deploy-backstage-with-score
    name: backstage
spec:
    owner: user:guest
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    annotations:
        github.com/project-slug: mathieu-benoit/deploy-backstage-with-score
    description: backend
    links:
        - icon: github
          title: Repository
          url: https://github.com/mathieu-benoit/deploy-backstage-with-score
    name: backstage-backend
    title: backend
spec:
    dependsOn:
        - resource:shared-dns
        - resource:backstage-backend-pg
    lifecycle: experimental
    owner: user:guest
    system: backstage
    type: service
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    annotations:
        github.com/project-slug: mathieu-benoit/deploy-backstage-with-score
    description: frontend
    links:
        - icon: github
          title: Repository
          url: https://github.com/mathieu-benoit/deploy-backstage-with-score
    name: backstage-frontend
    title: frontend
spec:
    dependsOn:
        - component:backstage-backend
        - resource:shared-dns
    lifecycle: experimental
    owner: user:guest
    system: backstage
    type: service
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
    description: backstage-backend-pg
    name: backstage-backend-pg
    title: pg
spec:
    owner: user:guest
    system: backstage
    type: postgres-instance
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
    description: backstage-frontend-backend
    name: backstage-frontend-backend
    title: backend
spec:
    owner: user:guest
    system: backstage
    type: service
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
    description: shared-dns
    name: shared-dns
    title: dns
spec:
    owner: user:guest
    system: backstage
    type: dns
