FROM --platform=$BUILDPLATFORM node:24-alpine@sha256:c921b97d4b74f51744057454b306b418cf693865e73b8100559189605f6955b8 AS build
RUN mkdir /app
COPY . /app
WORKDIR /app
RUN yarn install
RUN yarn workspace app build

FROM nginxinc/nginx-unprivileged:1.29.3-alpine-slim@sha256:d9def221bf58500eb9d2f896367d149af317dce65a67bfdd1260754a4a8bc073
ARG UID=101
USER root
RUN apk add --no-cache jq && rm -rf /var/lib/apk/lists/*
COPY --from=build /app/packages/app/dist /usr/share/nginx/html
RUN chown -R $UID:0 /usr/share/nginx/html/
RUN chmod -R g+w /usr/share/nginx/html/
COPY container-config/default.conf.template /etc/nginx/templates/default.conf.template
COPY container-config/inject-config.sh /docker-entrypoint.d/40-inject-config.sh
USER $UID
ENV PORT=8080
