FROM --platform=$BUILDPLATFORM node:22-alpine@sha256:9632533eda8061fc1e9960cfb3f8762781c07a00ee7317f5dc0e13c05e15166f AS build
RUN mkdir /app
COPY . /app
WORKDIR /app
RUN yarn install
RUN yarn workspace app build

FROM nginxinc/nginx-unprivileged:1.29.3-alpine-slim@sha256:a6bec37058b9047ece799c01d98dc6d5aa0542b6583cc69f187652f91331a752
ARG UID=101
USER root
RUN apk add --no-cache jq && rm -rf /var/lib/apk/lists/*
COPY --from=build /app/packages/app/dist /usr/share/nginx/html
RUN chown -R $UID:0 /usr/share/nginx/html/
RUN chmod -R g+w /usr/share/nginx/html/
COPY container-config/default.conf.template /etc/nginx/templates/default.conf.template
COPY container-config/inject-config.sh /docker-entrypoint.d/40-inject-config.sh
USER $UID
ENV PORT=8080
