name: ci
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  scan-and-compare-monolith:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Docker
        uses: docker/setup-docker-action@6d7cfa65f60a9dda7b46e5513fa982536f3c9877 #v5.3.0
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: docker login docker.io
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - name: Build container image from PR branch
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
          sbom: true
          tags: backstage:pr-${{ github.event.number }}
      - name: docker images
        run: |
          docker images
      - name: checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.base_ref }}
      - name: Build container image from main branch
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
          sbom: true
          tags: backstage:main
      - name: docker images
        run: |
          docker images
      - name: Docker Scout
        uses: docker/scout-action@2688993af7bafd6ba8c6a74ec652442be91dd82b # v1.23.1
        with:
          command: compare
          image: local://backstage:pr-${{ github.event.number }}
          to: local://backstage:main
          write-comment: true
          keep-previous-comments: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
  scan-and-compare-frontend:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Docker
        uses: docker/setup-docker-action@6d7cfa65f60a9dda7b46e5513fa982536f3c9877 #v5.3.0
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: docker login docker.io
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
      - name: remove frontend from backend
        run: |
          export YARN_ENABLE_IMMUTABLE_INSTALLS=false
          make remove-frontend-from-backend
      - name: Build container image from PR branch
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: Dockerfile.frontend
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
          sbom: true
          tags: frontend:pr-${{ github.event.number }}
      - name: docker images
        run: |
          docker images
      - name: checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.base_ref }}
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
      - name: remove frontend from backend
        run: |
          export YARN_ENABLE_IMMUTABLE_INSTALLS=false
          make remove-frontend-from-backend
      - name: Build container image from main branch
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: Dockerfile.frontend
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
          sbom: true
          tags: frontend:main
      - name: docker images
        run: |
          docker images
      - name: Docker Scout
        uses: docker/scout-action@2688993af7bafd6ba8c6a74ec652442be91dd82b # v1.23.1
        with:
          command: compare
          image: local://frontend:pr-${{ github.event.number }}
          to: local://frontend:main
          write-comment: true
          keep-previous-comments: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
  #multi-arch-build-frontend-container:
  #  uses: docker/github-builder/.github/workflows/build.yml@abff7868c866c54704b6afa9ad5871948ca97334 # v1.1.0
  #  with:
  #    output: image
  #    push: false
  #    platforms: linux/amd64,linux/arm64
  #    runner: amd64
  #    setup-qemu: true
  #    sbom: true
  #    cache: true
  #    context: .
  #    file: Dockerfile.frontend
  #    set-meta-labels: true
  #    set-meta-annotations: true
  #    meta-images: |
  #      frontend
  #    meta-tags: |
  #      type=ref,event=pr
  #multi-arch-build-backend-container:
  #  uses: docker/github-builder/.github/workflows/build.yml@abff7868c866c54704b6afa9ad5871948ca97334 # v1.1.0
  #  with:
  #    output: image
  #    push: false
  #    platforms: linux/amd64,linux/arm64
  #    sbom: true
  #    cache: true
  #    context: .
  #    file: Dockerfile
  #    set-meta-labels: true
  #    set-meta-annotations: true
  #    meta-images: |
  #      backend
  #    meta-tags: |
  #      type=ref,event=pr
  #  secrets:
  #    registry-auths: |
  #      - registry: docker.io
  #        username: ${{ secrets.DOCKER_USER }}
  #        password: ${{ secrets.DOCKER_PAT }}
  build-and-test-monolith:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
      - name: Check git diff is clean (all files generated should be committed)
        run: |
          node --version
          yarn install
          git diff --exit-code
      - name: install score-compose
        uses: score-spec/setup-score@888a7deafd396c3f3f05e00d2d9b0ab225799ac0 # v3.2.4
        with:
          file: score-compose
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"
      - name: docker login docker.io
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: make compose-monolith-test
        run: |
          make compose-monolith-test
      - name: install score-k8s
        uses: score-spec/setup-score@888a7deafd396c3f3f05e00d2d9b0ab225799ac0 # v3.2.4
        with:
          file: score-k8s
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"
      - name: make k8s-monolith-test
        run: |
          make kind-create-cluster
          make kind-load-monolith-image
          make k8s-monolith-test
  build-and-test-split:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
      - name: Check git diff is clean (all files generated should be committed)
        run: |
          node --version
          yarn install
          git diff --exit-code
      - name: remove frontend from backend
        run: |
          export YARN_ENABLE_IMMUTABLE_INSTALLS=false
          make remove-frontend-from-backend
      - name: install score-compose
        uses: score-spec/setup-score@888a7deafd396c3f3f05e00d2d9b0ab225799ac0 # v3.2.4
        with:
          file: score-compose
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"
      - name: docker login docker.io
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: make compose-split-test
        run: |
          make compose-split-test
      - name: install score-k8s
        uses: score-spec/setup-score@888a7deafd396c3f3f05e00d2d9b0ab225799ac0 # v3.2.4
        with:
          file: score-k8s
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"
      - name: make k8s-split-test
        run: |
          make kind-create-cluster
          make kind-load-split-images
          make k8s-split-test
