name: Upgrade Backstage version
permissions:
  contents: write
  id-token: write
  pull-requests: write
on:
  workflow_dispatch:
jobs:
  upgrade-backstage-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
      - name: yarn backstage-cli versions:bump
        run: |
          export YARN_ENABLE_IMMUTABLE_INSTALLS=false
          yarn install
          yarn backstage-cli versions:bump
          echo "BACKSTAGE_VERSION=$(curl -sL https://api.github.com/repos/backstage/backstage/releases/latest | jq -r .tag_name)" >> ${{ github.env }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Upgrade Backstage version to ${{ env.BACKSTAGE_VERSION }}
          title: Upgrade Backstage version to ${{ env.BACKSTAGE_VERSION }}
          body: |
            Upgrade Backstage version to ${{ env.BACKSTAGE_VERSION }}:
            https://github.com/backstage/backstage/releases/tag/${{ env.BACKSTAGE_VERSION }}
          branch: upgrade-backstage
          delete-branch: true
